name: web_haptics_example
description: Demo app for the web_haptics package.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  web_haptics:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
